/usr/local/bin/python3 emddNew3.py -n 3 -s 1
/usr/local/bin/python3 emddNew3.py -n 3 -s 2
/usr/local/bin/python3 emddNew3.py -n 3 -s 3
/usr/local/bin/python3 emddNew3.py -n 3 -s 4
/usr/local/bin/python3 emddNew3.py -n 3 -s 5
/usr/local/bin/python3 emddNew3.py -n 3 -s 6
/usr/local/bin/python3 emddNew3.py -n 3 -s 7
/usr/local/bin/python3 emddNew3.py -n 3 -s 8
/usr/local/bin/python3 emddNew3.py -n 3 -s 9
/usr/local/bin/python3 emddNew3.py -n 3 -s 10
/usr/local/bin/python3 emddNew3.py -n 3 -s 11
/usr/local/bin/python3 emddNew3.py -n 3 -s 12
/usr/local/bin/python3 emddNew3.py -n 3 -s 13
/usr/local/bin/python3 emddNew3.py -n 3 -s 14
/usr/local/bin/python3 emddNew3.py -n 3 -s 15
/usr/local/bin/python3 emddNew3.py -n 3 -s 16
/usr/local/bin/python3 emddNew3.py -n 3 -s 17
/usr/local/bin/python3 emddNew3.py -n 3 -s 18
/usr/local/bin/python3 emddNew3.py -n 3 -s 19
/usr/local/bin/python3 emddNew3.py -n 3 -s 20
